FROM node:18.19

WORKDIR /clusterio

VOLUME /clusterio/database
VOLUME /clusterio/custom_plugin

RUN echo '{"name":"clusterio-install","private":"true"}' > package.json
RUN npm install @clusterio/controller

RUN npm install discord.js mongodb
RUN echo '[["custom_plugin","/clusterio/custom_plugin"]]' > plugin-list.json
RUN perl -p -i -e 's|\${dir}\${name}|\${dir}\/\${name}|g' node_modules/\@clusterio/lib/dist/src/file_ops.js

EXPOSE 8080
ENTRYPOINT [ "./node_modules/.bin/clusteriocontroller", "run", "--config=/clusterio/database/config-controller.json" ]
