version: '3'

services:
  clusterio-master:
    image: awesome/master
    build:
      context: .
      dockerfile: Dockerfile-master
    volumes:
     - "./database:/clusterio/database"
     - "./custom_plugin:/clusterio/custom_plugin:ro"
    ports:
     - "8080:8080"

  clusterio-slave:
    image: awesome/slave
    build:
      context: .
      dockerfile: Dockerfile-slave
    volumes:
     - "./database-slave:/clusterio/database"
     - "./custom_plugin:/clusterio/custom_plugin:ro"
     - "./factorio:/factorio:ro"
     - "./instances:/instances"
    ports:
     - "34197:34197/udp"
     - "34679:34679/udp"
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ThisIsNotExposedPublically
    expose:
      - 27017
    volumes:
      - "./mongodb:/data/db"