version: '3'

services:
  clusterio-controller:
    image: awesome/controller
    build:
      context: .
      dockerfile: Dockerfile-controller
    volumes:
     - "./database:/clusterio/database"
     - "./custom_plugin:/clusterio/custom_plugin:ro"
    ports:
     - "8081:8080"

  clusterio-host:
    image: awesome/host
    build:
      context: .
      dockerfile: Dockerfile-host
    volumes:
     - "./database:/clusterio/database"
     - "./custom_plugin:/clusterio/custom_plugin:ro"
     - "./factorio:/factorio:ro"
     - "./instances:/instances"
    ports:
     - "34197:34197/udp"
     - "34679:34679/udp"
     - "34921:34921/udp"

  mongodb:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ThisIsNotExposedPublically
    expose:
      - 27017
    volumes:
      - "./mongodb:/data/db"
